In [90]:
import pandas as pd
import matplotlib.pyplot as plt

In [73]:
customer_df = pd.read_csv("D:/Study & Practice/Ecommerce_Data_Analysis/Ecommerce_Project/Datasets/customer_master.csv")
order_df = pd.read_csv("D:/Study & Practice/Ecommerce_Data_Analysis/Ecommerce_Project/Datasets/order_items.csv")
product_df = pd.read_csv("D:/Study & Practice/Ecommerce_Data_Analysis/Ecommerce_Project/Datasets/product_catalog.csv")
df = pd.read_csv("D:/Study & Practice/Ecommerce_Data_Analysis/Ecommerce_Project/Datasets/ecommerce_sales_customer_analytics_150k.csv")

In [74]:
df["order_date"]

0          11/6/2023
1         12/24/2025
2           7/5/2021
3          1/21/2023
4          5/13/2022
             ...
138111     9/27/2025
138112     7/22/2023
138113      9/8/2025
138114      4/6/2022
138115    11/23/2022
Name: order_date, Length: 138116, dtype: str

In [75]:
df["order_date"] = pd.to_datetime(df["order_date"])
df["order_year"] = df["order_date"].dt.year
df["order_month"] = df["order_date"].dt.month_name()

In [76]:
grouped_orders = df.groupby(["order_year", "order_month"])["order_id"].size().reset_index(name = "order_count")
pivot_data = grouped_orders.pivot(index="order_month", columns = "order_year", values="order_count")

months_order = [
    "January", "February", "March", "April", "May", "June", 
    "July", "August", "September", "October", "November", "December"
]
monthly_orders = pivot_data.reindex(months_order)
monthly_orders

order_year   2021  2022  2023  2024  2025
order_month
January      1906  1934  1926  1965  1962
February     1565  1615  1585  1617  1645
March        2166  2126  2134  2202  2194
April        1943  2008  2040  2123  2006
May          2096  2041  2054  2048  1999
June         2203  2174  2189  2176  2138
July         2036  2011  2010  2029  2121
August       2474  2349  2484  2394  2363
September    2134  2124  2190  2181  2226
October      2324  2333  2347  2293  2285
November     3139  3257  3177  3297  3191
December     3568  3592  3496  3443  3468

In [82]:
delivery_status = df.groupby("delivery_status").size().reset_index(name="order_count")

In [83]:
delivery_status

  delivery_status  order_count
0       Cancelled        24557
1         Delayed        16886
2           Early         9757
3         On Time        86916

In [88]:
review_sentiments = df.groupby(["customer_country","review_sentiment"]).size().reset_index(name="review_count")
review_sentiments

   customer_country review_sentiment  review_count
0         Australia         Negative            32
1         Australia          Neutral          1706
2         Australia         Positive          3810
3            Canada         Negative            47
4            Canada          Neutral          1681
5            Canada         Positive          3997
6           Germany         Negative            67
7           Germany          Neutral          2951
8           Germany         Positive          6465
9             India         Negative            28
10            India          Neutral          1496
11            India         Positive          3194
12              UAE         Negative            24
13              UAE          Neutral          1060
14              UAE         Positive          2371
15               UK         Negative           108
16               UK          Neutral          5114
17               UK         Positive         11430
18              USA         Negative           486
19              USA          Neutral         20676
20              USA         Positive         46816

In [89]:
df.customer_lifetime_value

0         12459.68
1         13032.48
2          6159.44
3          5638.30
4         13240.10
            ...
138111    18182.63
138112    10004.74
138113    16442.68
138114     8047.00
138115     4107.38
Name: customer_lifetime_value, Length: 138116, dtype: float64

In [114]:
profit_by_year = df.groupby("order_year")["profit"].sum().reset_index(name="total_profit")

In [117]:
profit_by_year

   order_year  total_profit
0        2021   15325651.87
1        2022   15167978.69
2        2023   15247695.95
3        2024   15292965.09
4        2025   15112104.16

In [126]:
return_order = df.query("order_status == 'Returned'")
return_order_by_country = return_order.groupby(["customer_country", "return_reason"]).size()
return_order_by_country

customer_country  return_reason
Australia         Changed Mind                66
                  Damaged Product             59
                  Defective Product           61
                  Late Delivery               60
                  Other                       56
                  Product Not as Expected     55
                  Size Issue                  53
                  Wrong Product               65
Canada            Changed Mind                65
                  Damaged Product             58
                  Defective Product           71
                  Late Delivery               59
                  Other                       61
                  Product Not as Expected     66
                  Size Issue                  59
                  Wrong Product               74
Germany           Changed Mind               112
                  Damaged Product             94
                  Defective Product          100
                  Late Delivery              101
                  Other                      100
                  Product Not as Expected    103
                  Size Issue                 100
                  Wrong Product              119
India             Changed Mind                61
                  Damaged Product             42
                  Defective Product           53
                  Late Delivery               48
                  Other                       51
                  Product Not as Expected     46
                  Size Issue                  49
                  Wrong Product               43
UAE               Changed Mind                40
                  Damaged Product             43
                  Defective Product           31
                  Late Delivery               28
                  Other                       27
                  Product Not as Expected     35
                  Size Issue                  26
                  Wrong Product               27
UK                Changed Mind               159
                  Damaged Product            165
                  Defective Product          172
                  Late Delivery              171
                  Other                      181
                  Product Not as Expected    169
                  Size Issue                 168
                  Wrong Product              205
USA               Changed Mind               701
                  Damaged Product            677
                  Defective Product          686
                  Late Delivery              705
                  Other                      732
                  Product Not as Expected    673
                  Size Issue                 727
                  Wrong Product              704
dtype: int64